name: 体验actions工作流
run-name: ${{ github.actor }} is testing out GitHub Actions 名称(run)
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "卧1槽The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "卧2槽his job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "卧3槽The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "卧4槽The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "卧5槽he workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
